networks:
  web:
    external: false

volumes:
  uploads:
  node-cache:
  pnpm-cache:
  pnpm-store:
  app-modules:
  demo-modules:
  forms-modules:
  server-modules:
  signaling-server-modules:
  where-are-you-at-modules:

services:
  traefik:
    image: 'traefik:${TRAEFIK_VERSION}'
    container_name: flottform-traefik
    restart: always
    command:
      - '--api=true'
      - '--api.dashboard=false'
      - '--api.insecure=false'
      # Enabling docker provider
      - '--providers.docker=true'
      # Do not expose containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=web'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.leresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.leresolver.acme.email=joern.bernhardt+letsencrypt@compose.us'
      - '--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json'
      - '--configFile=/traefik/traefik.yml'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.${HOST}`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls.certresolver=leresolver'
      - 'traefik.http.routers.dashboard.service=api@internal'
      # global redirect to https
      - 'traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=web'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker'
      # middleware redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/local/traefik/letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/traefik'
    networks:
      - 'web'

  signaling-server:
    build:
      args:
        NODE_VERSION: '${NODE_VERSION}'
      context: .
      dockerfile: ./Dockerfile
      target: runner
    container_name: flottform-signaling-server
    working_dir: '/app'
    entrypoint: './docker-entrypoint.sh'
    command: 'node servers/signaling-server/build'
    restart: always
    environment:
      - 'ADDRESS_HEADER=x-real-ip'
      - 'PROTOCOL_HEADER=x-forwarded-proto'
      - 'HOST_HEADER=x-forwarded-host'
      - 'PORT_HEADER=x-forwarded-port'
      - 'ALLOWED_ORIGINS=https://${HOST},https://where-are-you.at'
      - 'AUTH_KEY=${AUTH_KEY}'
      - 'ICE_SERVERS_CONFIGURATION=${ICE_SERVERS_CONFIGURATION}'
      - 'ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING}'
      - 'DEBUG_MODE=${DEBUG_MODE}'
      - 'PUBLIC_IS_ONLINE_DEMO=true'
    volumes:
      - 'app-modules:/app/node_modules'
      - 'demo-modules:/app/servers/demo/node_modules'
      - 'forms-modules:/app/flottform/forms/node_modules'
      - 'server-modules:/app/flottform/server/node_modules'
      - 'signaling-server-modules:/app/servers/signaling-server/node_modules'
      - 'where-are-you-at-modules:/app/servers/where-are-you-at/node_modules'
      - 'node-cache:/root/.cache'
      - 'pnpm-cache:/root/.npm'
      - 'pnpm-store:/app/.pnpm-store'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.services.flottform-signaling-server.loadbalancer.server.port=3000'
      - 'traefik.http.routers.flottform-signaling-server.priority=100'
      - 'traefik.http.routers.flottform-signaling-server.rule=Host(`${HOST}`) && PathPrefix(`/flottform/`)'
      - 'traefik.http.routers.flottform-signaling-server.service=flottform-signaling-server'
      - 'traefik.http.routers.flottform-signaling-server.entrypoints=websecure'
      - 'traefik.http.routers.flottform-signaling-server.tls.certresolver=leresolver'
    networks:
      - 'web'

  demo:
    build:
      args:
        NODE_VERSION: '${NODE_VERSION}'
      context: .
      dockerfile: ./Dockerfile
      target: runner
    container_name: flottform-demo
    working_dir: '/app'
    entrypoint: './docker-entrypoint.sh'
    command: 'node servers/demo/build'
    restart: always
    environment:
      - 'BODY_SIZE_LIMIT=33554432'
      - 'ADDRESS_HEADER=x-real-ip'
      - 'PROTOCOL_HEADER=x-forwarded-proto'
      - 'HOST_HEADER=x-forwarded-host'
      - 'PORT_HEADER=x-forwarded-port'
      - 'PUBLIC_FLOTTFORM_SERVER_BASE=https://${HOST}/flottform'
      - 'PUBLIC_IS_ONLINE_DEMO=true'
      - 'UPLOAD_FOLDER=/app/servers/demo/static/uploads'
    volumes:
      - 'app-modules:/app/node_modules'
      - 'demo-modules:/app/servers/demo/node_modules'
      - 'forms-modules:/app/flottform/forms/node_modules'
      - 'server-modules:/app/flottform/server/node_modules'
      - 'signaling-server-modules:/app/servers/signaling-server/node_modules'
      - 'where-are-you-at-modules:/app/servers/where-are-you-at/node_modules'
      - 'uploads:/app/servers/demo/static/uploads'
      - 'node-cache:/root/.cache'
      - 'pnpm-cache:/root/.npm'
      - 'pnpm-store:/app/.pnpm-store'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.services.flottform-demo.loadbalancer.server.port=3000'
      - 'traefik.http.routers.flottform-demo.priority=50'
      - 'traefik.http.routers.flottform-demo.service=flottform-demo'
      - 'traefik.http.routers.flottform-demo.rule=Host(`${HOST}`)'
      - 'traefik.http.routers.flottform-demo.entrypoints=websecure'
      - 'traefik.http.routers.flottform-demo.tls.certresolver=leresolver'
    networks:
      - 'web'

  where-are-you-at:
    build:
      args:
        NODE_VERSION: '${NODE_VERSION}'
      context: .
      dockerfile: ./Dockerfile
      target: runner
    container_name: where-are-you-at
    working_dir: '/app'
    entrypoint: './docker-entrypoint.sh'
    command: 'node servers/where-are-you-at/build'
    restart: always
    environment:
      - 'BODY_SIZE_LIMIT=33554432'
      - 'ADDRESS_HEADER=x-real-ip'
      - 'PROTOCOL_HEADER=x-forwarded-proto'
      - 'HOST_HEADER=x-forwarded-host'
      - 'PORT_HEADER=x-forwarded-port'
      - 'PUBLIC_FLOTTFORM_SERVER_BASE=https://${HOST}/flottform'
      - 'PUBLIC_IS_ONLINE_DEMO=true'
    volumes:
      - 'app-modules:/app/node_modules'
      - 'demo-modules:/app/servers/demo/node_modules'
      - 'forms-modules:/app/flottform/forms/node_modules'
      - 'server-modules:/app/flottform/server/node_modules'
      - 'signaling-server-modules:/app/servers/signaling-server/node_modules'
      - 'where-are-you-at-modules:/app/servers/where-are-you-at/node_modules'
      - 'node-cache:/root/.cache'
      - 'pnpm-cache:/root/.npm'
      - 'pnpm-store:/app/.pnpm-store'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.services.where-are-you-at.loadbalancer.server.port=3000'
      - 'traefik.http.routers.where-are-you-at.priority=50'
      - 'traefik.http.routers.where-are-you-at.service=where-are-you-at'
      - 'traefik.http.routers.where-are-you-at.rule=Host(`where-are-you.at`)'
      - 'traefik.http.routers.where-are-you-at.entrypoints=websecure'
      - 'traefik.http.routers.where-are-you-at.tls.certresolver=leresolver'
    networks:
      - 'web'
